Algoritmo "nome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
     nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o seu nome: ")
leia(nome)
escreva("Olà, " , nome , ". Seja bem-vindo(a)")

Fimalgoritmo